from google.appengine.ext import db

##################################################################################################
# TODO - This module filename is misnamed - 
#        It does not just contain address related items, 
#        but rather mostly lists of items that can be chosen in selectBoxes on input forms. 
##################################################################################################
class OrderStates(db.Model):  #this is never stored in database 
     value     = db.StringProperty()  
     selected  = db.BooleanProperty()  

orderStates = []
orderStates.append(OrderStates(value="Select One",selected=True))
orderStates.append(OrderStates(value="open",selected=False))
orderStates.append(OrderStates(value="open.not_running",selected=False))
orderStates.append(OrderStates(value="open.not_running.not_started",selected=False))
orderStates.append(OrderStates(value="open.not_running.suspended",selected=False))
orderStates.append(OrderStates(value="open.running",selected=False))
orderStates.append(OrderStates(value="closed",selected=False))
orderStates.append(OrderStates(value="closed.completed",selected=False))
orderStates.append(OrderStates(value="closed.aborted",selected=False))
orderStates.append(OrderStates(value="closed.aborted.byclient",selected=False))
orderStates.append(OrderStates(value="closed.aborted.byserver",selected=False))

class OrderFinancialStates(db.Model):  #this is never stored in database 
     value     = db.StringProperty()  
     selected  = db.BooleanProperty()  

orderFinancialStates = []
orderFinancialStates.append(OrderFinancialStates(value="Select One",selected=True))
orderFinancialStates.append(OrderFinancialStates(value="PayPal.not_paid",selected=False))
orderFinancialStates.append(OrderFinancialStates(value="PayPal.checkout_cancelled",selected=False))
orderFinancialStates.append(OrderFinancialStates(value="PayPal.user_cancelled",selected=False))
orderFinancialStates.append(OrderFinancialStates(value="PayPal.paid",selected=False))
orderFinancialStates.append(OrderFinancialStates(value="PayPal.pending",selected=False))
orderFinancialStates.append(OrderFinancialStates(value="Complementary",selected=False))


class Registrars(db.Model):  #this is never stored in database 
     value = db.StringProperty()  
     selected  = db.BooleanProperty()  

registrars = []
registrars.append(Registrars(value="Select One",selected=True))
registrars.append(Registrars(value="Register.com",selected=False)) 
registrars.append(Registrars(value="GoDaddy.com",selected=False)) 
registrars.append(Registrars(value="NetworkSolutions.com",selected=False)) 
registrars.append(Registrars(value="Enom.com",selected=False)) 
registrars.append(Registrars(value="Dotster.com",selected=False)) 
registrars.append(Registrars(value="NameCheap.com",selected=False)) 
registrars.append(Registrars(value="ItsYourDomain.com",selected=False)) 
registrars.append(Registrars(value="1and1.com",selected=False)) 
registrars.append(Registrars(value="DomainRegistrationz.com",selected=False)) 
registrars.append(Registrars(value="DirectNIC.com",selected=False)) 
registrars.append(Registrars(value="Domain.com",selected=False)) 
registrars.append(Registrars(value="If your registrar does not appear, please type it in below",selected=False)) 



class TimeZones(db.Model): #this is never stored in database 
     description = db.StringProperty()  
     value = db.FloatProperty()
     selected  = db.BooleanProperty() 

timezones = []
timezones.append(TimeZones(value=-12.0,description="(GMT -12:00) Eniwetok, Kwajalein",selected=False)) 
timezones.append(TimeZones(value=-11.0,description="(GMT -11:00) Midway Island, Samoa",selected=False)) 
timezones.append(TimeZones(value=-10.0,description="(GMT -10:00) Hawaii",selected=False)) 
timezones.append(TimeZones(value=-09.0,description="(GMT -9:00) Alaska",selected=False)) 
timezones.append(TimeZones(value=-08.0,description="(GMT -8:00) Pacific Time (US &amp; Canada)",selected=False)) 
timezones.append(TimeZones(value=-07.0,description="(GMT -7:00) Mountain Time (US &amp; Canada)",selected=False)) 
timezones.append(TimeZones(value=-06.0,description="(GMT -6:00) Central Time (US &amp; Canada), Mexico City",selected=False)) 
timezones.append(TimeZones(value=-05.0,description="(GMT -5:00) Eastern Time (US &amp; Canada), Bogota, Lima",selected=False)) 
timezones.append(TimeZones(value=-04.0,description="(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz",selected=False)) 
timezones.append(TimeZones(value=-03.5,description="(GMT -3:30) Newfoundland",selected=False)) 
timezones.append(TimeZones(value=-02.0,description="(GMT -3:00) Brazil, Buenos Aires, Georgetown",selected=False)) 
timezones.append(TimeZones(value=-01.0,description="(GMT -2:00) Mid-Atlantic",selected=False)) 
timezones.append(TimeZones(value=-01.0,description="(GMT -1:00 hour) Azores, Cape Verde Islands",selected=False)) 
timezones.append(TimeZones(value= 00.0,description="(GMT) Western Europe Time, London, Lisbon, Casablanca",selected=False)) 
timezones.append(TimeZones(value= 01.0,description="(GMT +1:00 hour) Brussels, Copenhagen, Madrid, Paris",selected=False)) 
timezones.append(TimeZones(value= 02.0,description="(GMT +2:00) Kaliningrad, South Africa",selected=False)) 
timezones.append(TimeZones(value= 03.0,description="(GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg",selected=False)) 
timezones.append(TimeZones(value= 03.5,description="(GMT +3:30) Tehran",selected=False)) 
timezones.append(TimeZones(value= 04.0,description="(GMT +4:00) Abu Dhabi, Muscat, Baku, Tbilisi",selected=False)) 
timezones.append(TimeZones(value= 04.5,description="(GMT +4:30) Kabul",selected=False)) 
timezones.append(TimeZones(value= 05.0,description="(GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent",selected=False)) 
timezones.append(TimeZones(value= 05.5,description="(GMT +5:30) Bombay, Calcutta, Madras, New Delhi",selected=False)) 
timezones.append(TimeZones(value= 05.75,description="(GMT +5:45) Kathmandu",selected=False)) 
timezones.append(TimeZones(value= 06.0,description="(GMT +6:00) Almaty, Dhaka, Colombo",selected=False)) 
timezones.append(TimeZones(value= 07.0,description="(GMT +7:00) Bangkok, Hanoi, Jakarta",selected=False)) 
timezones.append(TimeZones(value= 08.0,description="(GMT +8:00) Beijing, Perth, Singapore, Hong Kong",selected=False)) 
timezones.append(TimeZones(value= 09.0,description="(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk",selected=False)) 
timezones.append(TimeZones(value= 09.5,description="(GMT +9:30) Adelaide, Darwin",selected=False)) 
timezones.append(TimeZones(value= 10.0,description="(GMT +10:00) Eastern Australia, Guam, Vladivostok",selected=False)) 
timezones.append(TimeZones(value= 11.0,description="(GMT +11:00) Magadan, Solomon Islands, New Caledonia",selected=False)) 
timezones.append(TimeZones(value= 12.0,description="(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka",selected=False)) 

class CellProviders(db.Model): #(carriers) this is never stored in database CURRENTLY NOT USED 
     description = db.StringProperty()  
     value = db.StringProperty()  
     selected  = db.BooleanProperty() 
cellproviders=[]
cellproviders.append(CellProviders(value="Select One",description="Select One",selected=False))
cellproviders.append(CellProviders(value="AT&amp;T",description="AT&T",selected=False))
cellproviders.append(CellProviders(value="Verizon",description="Verizon",selected=False))
cellproviders.append(CellProviders(value="Sprint",description="Sprint",selected=False))
cellproviders.append(CellProviders(value="TMobile",description="TMobile",selected=False))
cellproviders.append(CellProviders(value="Vodafone",description="Vodafone",selected=False))
cellproviders.append(CellProviders(value="China Mobile",description="China Mobile",selected=False))
cellproviders.append(CellProviders(value="Movistar",description="Movistar",selected=False))
cellproviders.append(CellProviders(value="T-Mobile",description="T-Mobile",selected=False))
cellproviders.append(CellProviders(value="Other",description="Other",selected=False))

class States(db.Model): #this is never stored in database 
     description = db.StringProperty()  
     country = db.StringProperty()  
     value = db.StringProperty()  
     selected  = db.BooleanProperty() 
states=[]
states.append(States(value="AK",description="Alaska",country="USA",selected=False)) 
states.append(States(value="AL",description="Alabama",country="USA",selected=False)) 
states.append(States(value="AR",description="Arkansas",country="USA",selected=False)) 
states.append(States(value="AZ",description="Arizona",country="USA",selected=False)) 
states.append(States(value="CA",description="California",country="USA",selected=False)) 
states.append(States(value="CO",description="Colorado",country="USA",selected=False)) 
states.append(States(value="CT",description="Connecticut",country="USA",selected=False)) 
states.append(States(value="DC",description="District of Columbia",country="USA",selected=False)) 
states.append(States(value="DE",description="Delaware",country="USA",selected=False)) 
states.append(States(value="FL",description="Florida",country="USA",selected=False)) 
states.append(States(value="GA",description="Georgia",country="USA",selected=False)) 
states.append(States(value="HI",description="Hawaii",country="USA",selected=False)) 
states.append(States(value="IA",description="Iowa",country="USA",selected=False)) 
states.append(States(value="ID",description="Idaho",country="USA",selected=False)) 
states.append(States(value="IL",description="Illinois",country="USA",selected=False)) 
states.append(States(value="IN",description="Indiana",country="USA",selected=False)) 
states.append(States(value="KS",description="Kansas",country="USA",selected=False)) 
states.append(States(value="KY",description="Kentucky",country="USA",selected=False)) 
states.append(States(value="LA",description="Louisiana",country="USA",selected=False)) 
states.append(States(value="MA",description="Massachusetts",country="USA",selected=False)) 
states.append(States(value="MD",description="Maryland",country="USA",selected=False)) 
states.append(States(value="ME",description="Maine",country="USA",selected=False)) 
states.append(States(value="MI",description="Michigan",country="USA",selected=False)) 
states.append(States(value="MN",description="Minnesota",country="USA",selected=False)) 
states.append(States(value="MO",description="Missouri",country="USA",selected=False)) 
states.append(States(value="MS",description="Mississippi",country="USA",selected=False)) 
states.append(States(value="MT",description="Montana",country="USA",selected=False)) 
states.append(States(value="NC",description="North Carolina",country="USA",selected=False)) 
states.append(States(value="ND",description="North Dakota",country="USA",selected=False)) 
states.append(States(value="NE",description="Nebraska",country="USA",selected=False)) 
states.append(States(value="NH",description="New Hampshire",country="USA",selected=False)) 
states.append(States(value="NJ",description="New Jersey",country="USA",selected=False)) 
states.append(States(value="NM",description="New Mexico",country="USA",selected=False)) 
states.append(States(value="NV",description="Nevada",country="USA",selected=False)) 
states.append(States(value="NY",description="New York",country="USA",selected=False)) 
states.append(States(value="OH",description="Ohio",country="USA",selected=False)) 
states.append(States(value="OK",description="Oklahoma",country="USA",selected=False)) 
states.append(States(value="OR",description="Oregon",country="USA",selected=False)) 
states.append(States(value="PA",description="Pennsylvania",country="USA",selected=False)) 
states.append(States(value="PR",description="Puerto Rico",country="USA",selected=False)) 
states.append(States(value="RI",description="Rhode Island",country="USA",selected=False)) 
states.append(States(value="SC",description="South Carolina",country="USA",selected=False)) 
states.append(States(value="SD",description="South Dakota",country="USA",selected=False)) 
states.append(States(value="TN",description="Tennessee",country="USA",selected=False)) 
states.append(States(value="TX",description="Texas",country="USA",selected=False)) 
states.append(States(value="UT",description="Utah",country="USA",selected=False)) 
states.append(States(value="VA",description="Virginia",country="USA",selected=False)) 
states.append(States(value="VT",description="Vermont",country="USA",selected=False)) 
states.append(States(value="WA",description="Washington",country="USA",selected=False)) 
states.append(States(value="WI",description="Wisconsin",country="USA",selected=False)) 
states.append(States(value="WV",description="West Virginia",country="USA",selected=False)) 
states.append(States(value="WY",description="Wyoming",country="USA",selected=False)) 
states.append(States(value="AB",description="Alberta",country="Canada",selected=False)) 
states.append(States(value="BC",description="British Columbia",country="Canada",selected=False)) 
states.append(States(value="MB",description="Manitoba",country="Canada",selected=False)) 
states.append(States(value="NB",description="New Brunswick",country="Canada",selected=False)) 
states.append(States(value="NF",description="Newfoundland",country="Canada",selected=False)) 
states.append(States(value="NT",description="Northwest Territories",country="Canada",selected=False)) 
states.append(States(value="NS",description="Nova Scotia",country="Canada",selected=False)) 
states.append(States(value="NU",description="Nunavut",country="Canada",selected=False)) 
states.append(States(value="ON",description="Ontario",country="Canada",selected=False)) 
states.append(States(value="PE",description="Prince Edward Island",country="Canada",selected=False)) 
states.append(States(value="QC",description="Quebec",country="Canada",selected=False)) 
states.append(States(value="SK",description="Saskatchewan",country="Canada",selected=False)) 
states.append(States(value="YT",description="Yukon Territory",country="Canada",selected=False)) 
states.append(States(value="NA",description="Not Required",country="Other",selected=False)) 

continents=['North America', 'South America', 'Antarctica', 'Africa', 'Europe', 'Asia', 'Oceania']

class Countries(db.Model): #this is never stored in database 
     description = db.StringProperty()  
     continent = db.StringProperty()  
     value = db.StringProperty()  
     selected  = db.BooleanProperty() 
countries=[]
countries.append(Countries(value="226",description="United States",continent="North America", selected=False)) 
countries.append(Countries(value="007",description="Anguilla",continent="North America", selected=False)) 
countries.append(Countries(value="009",description="Antigua and Barbuda",continent="North America", selected=False)) 
countries.append(Countries(value="012",description="Aruba",continent="North America", selected=False)) 
countries.append(Countries(value="016",description="Bahamas",continent="North America", selected=False)) 
countries.append(Countries(value="019",description="Barbados",continent="North America", selected=False)) 
countries.append(Countries(value="022",description="Belize",continent="North America", selected=False)) 
countries.append(Countries(value="024",description="Bermuda",continent="North America", selected=False)) 
countries.append(Countries(value="233",description="Virgin Islands, British",continent="North America", selected=False)) 
countries.append(Countries(value="038",description="Canada",continent="North America", selected=False)) 
countries.append(Countries(value="040",description="Cayman Islands",continent="North America", selected=False)) 
countries.append(Countries(value="052",description="Costa Rica",continent="North America", selected=False)) 
countries.append(Countries(value="055",description="Cuba",continent="North America", selected=False)) 
countries.append(Countries(value="060",description="Dominica",continent="North America", selected=False)) 
countries.append(Countries(value="061",description="Dominican Republic",continent="North America", selected=False)) 
countries.append(Countries(value="064",description="El Salvador",continent="North America", selected=False)) 
countries.append(Countries(value="069",description="Falkland Islands (Malvinas)",continent="North America", selected=False)) 
countries.append(Countries(value="084",description="Greenland",continent="North America", selected=False)) 
countries.append(Countries(value="085",description="Grenada",continent="North America", selected=False)) 
countries.append(Countries(value="086",description="Guadeloupe",continent="North America", selected=False)) 
countries.append(Countries(value="088",description="Guatemala",continent="North America", selected=False)) 
countries.append(Countries(value="092",description="Haiti",continent="North America", selected=False)) 
countries.append(Countries(value="095",description="Honduras",continent="North America", selected=False)) 
countries.append(Countries(value="106",description="Jamaica",continent="North America", selected=False)) 
countries.append(Countries(value="134",description="Martinique",continent="North America", selected=False)) 
countries.append(Countries(value="138",description="Mexico",continent="North America", selected=False)) 
countries.append(Countries(value="143",description="Montserrat",continent="North America", selected=False)) 
countries.append(Countries(value="151",description="Netherlands Antilles",continent="North America", selected=False)) 
countries.append(Countries(value="154",description="Nicaragua",continent="North America", selected=False)) 
countries.append(Countries(value="165",description="Panama",continent="North America", selected=False)) 
countries.append(Countries(value="173",description="Puerto Rico",continent="North America", selected=False)) 
countries.append(Countries(value="180",description="Saint Kitts and Nevis",continent="North America", selected=False)) 
countries.append(Countries(value="181",description="Saint Lucia",continent="North America", selected=False)) 
countries.append(Countries(value="182",description="Saint Pierre and Miquelon",continent="North America", selected=False)) 
countries.append(Countries(value="183",description="Saint Vincent and The Grenadines",continent="North America", selected=False)) 
countries.append(Countries(value="216",description="Trinidad and Tobago",continent="North America", selected=False)) 
countries.append(Countries(value="220",description="Turks and Caicos Islands",continent="North America", selected=False)) 
countries.append(Countries(value="226",description="United States",continent="North America", selected=False)) 
countries.append(Countries(value="227",description="United States Minor Outlying Islands",continent="North America", selected=False)) 
countries.append(Countries(value="234",description="Virgin Islands, U.S.",continent="North America", selected=False)) 
countries.append(Countries(value="010",description="Argentina",continent="South America", selected=False)) 
countries.append(Countries(value="026",description="Bolivia",continent="South America", selected=False)) 
countries.append(Countries(value="030",description="Brazil",continent="South America", selected=False)) 
countries.append(Countries(value="043",description="Chile",continent="South America", selected=False)) 
countries.append(Countries(value="047",description="Colombia",continent="South America", selected=False)) 
countries.append(Countries(value="062",description="Ecuador",continent="South America", selected=False)) 
countries.append(Countries(value="074",description="French Guiana",continent="South America", selected=False)) 
countries.append(Countries(value="091",description="Guyana",continent="South America", selected=False)) 
countries.append(Countries(value="167",description="Paraguay",continent="South America", selected=False)) 
countries.append(Countries(value="168",description="Peru",continent="South America", selected=False)) 
countries.append(Countries(value="202",description="Suriname",continent="South America", selected=False)) 
countries.append(Countries(value="228",description="Uruguay",continent="South America", selected=False)) 
countries.append(Countries(value="231",description="Venezuela",continent="South America", selected=False)) 
countries.append(Countries(value="008",description="Antarctica",continent="Antarctica", selected=False)) 
countries.append(Countries(value="029",description="Bouvet Island",continent="Antarctica", selected=False)) 
countries.append(Countries(value="076",description="French Southern Territories",continent="Antarctica", selected=False)) 
countries.append(Countries(value="093",description="Heard Island and Mcdonald Islands",continent="Antarctica", selected=False)) 
countries.append(Countries(value="198",description="South Georgia and The South Sandwich Islands",continent="Antarctica", selected=False)) 
countries.append(Countries(value="003",description="Algeria",continent="Africa", selected=False)) 
countries.append(Countries(value="006",description="Angola",continent="Africa", selected=False)) 
countries.append(Countries(value="023",description="Benin",continent="Africa", selected=False)) 
countries.append(Countries(value="028",description="Botswana",continent="Africa", selected=False)) 
countries.append(Countries(value="034",description="Burkina Faso",continent="Africa", selected=False)) 
countries.append(Countries(value="035",description="Burundi",continent="Africa", selected=False)) 
countries.append(Countries(value="037",description="Cameroon",continent="Africa", selected=False)) 
countries.append(Countries(value="039",description="Cape Verde",continent="Africa", selected=False)) 
countries.append(Countries(value="041",description="Central African Republic",continent="Africa", selected=False)) 
countries.append(Countries(value="042",description="Chad",continent="Africa", selected=False)) 
countries.append(Countries(value="048",description="Comoros",continent="Africa", selected=False)) 
countries.append(Countries(value="049",description="Congo",continent="Africa", selected=False)) 
countries.append(Countries(value="050",description="Congo, The Democratic Republic of The",continent="Africa", selected=False)) 
countries.append(Countries(value="053",description="Cote D'ivoire",continent="Africa", selected=False)) 
countries.append(Countries(value="059",description="Djibouti",continent="Africa", selected=False)) 
countries.append(Countries(value="063",description="Egypt",continent="Africa", selected=False)) 
countries.append(Countries(value="065",description="Equatorial Guinea",continent="Africa", selected=False)) 
countries.append(Countries(value="066",description="Eritrea",continent="Africa", selected=False)) 
countries.append(Countries(value="068",description="Ethiopia",continent="Africa", selected=False)) 
countries.append(Countries(value="077",description="Gabon",continent="Africa", selected=False)) 
countries.append(Countries(value="078",description="Gambia",continent="Africa", selected=False)) 
countries.append(Countries(value="081",description="Ghana",continent="Africa", selected=False)) 
countries.append(Countries(value="089",description="Guinea",continent="Africa", selected=False)) 
countries.append(Countries(value="090",description="Guinea-bissau",continent="Africa", selected=False)) 
countries.append(Countries(value="110",description="Kenya",continent="Africa", selected=False)) 
countries.append(Countries(value="119",description="Lesotho",continent="Africa", selected=False)) 
countries.append(Countries(value="120",description="Liberia",continent="Africa", selected=False)) 
countries.append(Countries(value="121",description="Libyan Arab Jamahiriya",continent="Africa", selected=False)) 
countries.append(Countries(value="235",description="Wallis and Futuna",continent="Africa", selected=False)) 
countries.append(Countries(value="236",description="Western Sahara",continent="Africa", selected=False)) 
countries.append(Countries(value="237",description="Yemen",continent="Africa", selected=False)) 
countries.append(Countries(value="127",description="Madagascar",continent="Africa", selected=False)) 
countries.append(Countries(value="128",description="Malawi",continent="Africa", selected=False)) 
countries.append(Countries(value="131",description="Mali",continent="Africa", selected=False)) 
countries.append(Countries(value="135",description="Mauritania",continent="Africa", selected=False)) 
countries.append(Countries(value="136",description="Mauritius",continent="Africa", selected=False)) 
countries.append(Countries(value="137",description="Mayotte",continent="Africa", selected=False)) 
countries.append(Countries(value="144",description="Morocco",continent="Africa", selected=False)) 
countries.append(Countries(value="145",description="Mozambique",continent="Africa", selected=False)) 
countries.append(Countries(value="147",description="Namibia",continent="Africa", selected=False)) 
countries.append(Countries(value="155",description="Niger",continent="Africa", selected=False)) 
countries.append(Countries(value="156",description="Nigeria",continent="Africa", selected=False)) 
countries.append(Countries(value="175",description="Reunion",continent="Africa", selected=False)) 
countries.append(Countries(value="178",description="Rwanda",continent="Africa", selected=False)) 
countries.append(Countries(value="179",description="Saint Helena",continent="Africa", selected=False)) 
countries.append(Countries(value="186",description="Sao Tome and Principe",continent="Africa", selected=False)) 
countries.append(Countries(value="188",description="Senegal",continent="Africa", selected=False)) 
countries.append(Countries(value="190",description="Seychelles",continent="Africa", selected=False)) 
countries.append(Countries(value="191",description="Sierra Leone",continent="Africa", selected=False)) 
countries.append(Countries(value="196",description="Somalia",continent="Africa", selected=False)) 
countries.append(Countries(value="197",description="South Africa",continent="Africa", selected=False)) 
countries.append(Countries(value="201",description="Sudan",continent="Africa", selected=False)) 
countries.append(Countries(value="204",description="Swaziland",continent="Africa", selected=False)) 
countries.append(Countries(value="210",description="Tanzania, United Republic of",continent="Africa", selected=False)) 
countries.append(Countries(value="213",description="Togo",continent="Africa", selected=False)) 
countries.append(Countries(value="217",description="Tunisia",continent="Africa", selected=False)) 
countries.append(Countries(value="222",description="Uganda",continent="Africa", selected=False)) 
countries.append(Countries(value="238",description="Zambia",continent="Africa", selected=False)) 
countries.append(Countries(value="239",description="Zimbabwe",continent="Africa", selected=False)) 
countries.append(Countries(value="002",description="Albania",continent="Europe", selected=False)) 
countries.append(Countries(value="005",description="Andorra",continent="Europe", selected=False)) 
countries.append(Countries(value="011",description="Armenia",continent="Europe", selected=False)) 
countries.append(Countries(value="014",description="Austria",continent="Europe", selected=False)) 
countries.append(Countries(value="015",description="Azerbaijan",continent="Europe", selected=False)) 
countries.append(Countries(value="020",description="Belarus",continent="Europe", selected=False)) 
countries.append(Countries(value="021",description="Belgium",continent="Europe", selected=False)) 
countries.append(Countries(value="027",description="Bosnia and Herzegovina",continent="Europe", selected=False)) 
countries.append(Countries(value="033",description="Bulgaria",continent="Europe", selected=False)) 
countries.append(Countries(value="054",description="Croatia",continent="Europe", selected=False)) 
countries.append(Countries(value="056",description="Cyprus",continent="Europe", selected=False)) 
countries.append(Countries(value="057",description="Czech Republic",continent="Europe", selected=False)) 
countries.append(Countries(value="058",description="Denmark",continent="Europe", selected=False)) 
countries.append(Countries(value="067",description="Estonia",continent="Europe", selected=False)) 
countries.append(Countries(value="070",description="Faroe Islands",continent="Europe", selected=False)) 
countries.append(Countries(value="072",description="Finland",continent="Europe", selected=False)) 
countries.append(Countries(value="073",description="France",continent="Europe", selected=False)) 
countries.append(Countries(value="079",description="Georgia",continent="Europe", selected=False)) 
countries.append(Countries(value="080",description="Germany",continent="Europe", selected=False)) 
countries.append(Countries(value="082",description="Gibraltar",continent="Europe", selected=False)) 
countries.append(Countries(value="083",description="Greece",continent="Europe", selected=False)) 
countries.append(Countries(value="084",description="Greenland",continent="Europe", selected=False)) 
countries.append(Countries(value="097",description="Hungary",continent="Europe", selected=False)) 
countries.append(Countries(value="098",description="Iceland",continent="Europe", selected=False)) 
countries.append(Countries(value="103",description="Ireland",continent="Europe", selected=False)) 
countries.append(Countries(value="105",description="Italy",continent="Europe", selected=False)) 
countries.append(Countries(value="109",description="Kazakhstan",continent="Europe", selected=False)) 
countries.append(Countries(value="300",description="Kosovo",continent="Europe", selected=False)) 
countries.append(Countries(value="117",description="Latvia",continent="Europe", selected=False)) 
countries.append(Countries(value="122",description="Liechtenstein",continent="Europe", selected=False)) 
countries.append(Countries(value="123",description="Lithuania",continent="Europe", selected=False)) 
countries.append(Countries(value="124",description="Luxembourg",continent="Europe", selected=False)) 
countries.append(Countries(value="126",description="Macedonia",continent="Europe", selected=False)) 
countries.append(Countries(value="132",description="Malta",continent="Europe", selected=False)) 
countries.append(Countries(value="140",description="Moldova, Republic of",continent="Europe", selected=False)) 
countries.append(Countries(value="141",description="Monaco",continent="Europe", selected=False)) 
countries.append(Countries(value="301",description="Montenegro",continent="Europe", selected=False)) 
countries.append(Countries(value="150",description="Netherlands",continent="Europe", selected=False)) 
countries.append(Countries(value="160",description="Norway",continent="Europe", selected=False)) 
countries.append(Countries(value="171",description="Poland",continent="Europe", selected=False)) 
countries.append(Countries(value="172",description="Portugal",continent="Europe", selected=False)) 
countries.append(Countries(value="176",description="Romania",continent="Europe", selected=False)) 
countries.append(Countries(value="177",description="Russia",continent="Europe", selected=False)) 
countries.append(Countries(value="185",description="San Marino",continent="Europe", selected=False)) 
countries.append(Countries(value="189",description="Serbia and Montenegro",continent="Europe", selected=False)) 
countries.append(Countries(value="193",description="Slovakia",continent="Europe", selected=False)) 
countries.append(Countries(value="194",description="Slovenia",continent="Europe", selected=False)) 
countries.append(Countries(value="199",description="Spain",continent="Europe", selected=False)) 
countries.append(Countries(value="203",description="Svalbard and Jan Mayen",continent="Europe", selected=False)) 
countries.append(Countries(value="205",description="Sweden",continent="Europe", selected=False)) 
countries.append(Countries(value="206",description="Switzerland",continent="Europe", selected=False)) 
countries.append(Countries(value="218",description="Turkey",continent="Europe", selected=False)) 
countries.append(Countries(value="223",description="Ukraine",continent="Europe", selected=False)) 
countries.append(Countries(value="225",description="United Kingdom",continent="Europe", selected=False)) 
countries.append(Countries(value="094",description="Vatican City",continent="Europe", selected=False)) 
countries.append(Countries(value="001",description="Afghanistan",continent="Asia", selected=False)) 
countries.append(Countries(value="011",description="Armenia",continent="Asia", selected=False)) 
countries.append(Countries(value="015",description="Azerbaijan",continent="Asia", selected=False)) 
countries.append(Countries(value="017",description="Bahrain",continent="Asia", selected=False)) 
countries.append(Countries(value="018",description="Bangladesh",continent="Asia", selected=False)) 
countries.append(Countries(value="025",description="Bhutan",continent="Asia", selected=False)) 
countries.append(Countries(value="031",description="British Indian Ocean Territory",continent="Asia", selected=False)) 
countries.append(Countries(value="032",description="Brunei Darussalam",continent="Asia", selected=False)) 
countries.append(Countries(value="036",description="Cambodia",continent="Asia", selected=False)) 
countries.append(Countries(value="044",description="China",continent="Asia", selected=False)) 
countries.append(Countries(value="056",description="Cyprus",continent="Asia", selected=False)) 
countries.append(Countries(value="079",description="Georgia",continent="Asia", selected=False)) 
countries.append(Countries(value="096",description="Hong Kong",continent="Asia", selected=False)) 
countries.append(Countries(value="099",description="India",continent="Asia", selected=False)) 
countries.append(Countries(value="100",description="Indonesia",continent="Asia", selected=False)) 
countries.append(Countries(value="101",description="Iran",continent="Asia", selected=False)) 
countries.append(Countries(value="102",description="Iraq",continent="Asia", selected=False)) 
countries.append(Countries(value="104",description="Israel",continent="Asia", selected=False)) 
countries.append(Countries(value="107",description="Japan",continent="Asia", selected=False)) 
countries.append(Countries(value="108",description="Jordan",continent="Asia", selected=False)) 
countries.append(Countries(value="109",description="Kazakhstan",continent="Asia", selected=False)) 
countries.append(Countries(value="112",description="Korea, North",continent="Asia", selected=False)) 
countries.append(Countries(value="113",description="Korea, South",continent="Asia", selected=False)) 
countries.append(Countries(value="114",description="Kuwait",continent="Asia", selected=False)) 
countries.append(Countries(value="115",description="Kyrgyzstan",continent="Asia", selected=False)) 
countries.append(Countries(value="116",description="Laos",continent="Asia", selected=False)) 
countries.append(Countries(value="118",description="Lebanon",continent="Asia", selected=False)) 
countries.append(Countries(value="125",description="Macau",continent="Asia", selected=False)) 
countries.append(Countries(value="129",description="Malaysia",continent="Asia", selected=False)) 
countries.append(Countries(value="130",description="Maldives",continent="Asia", selected=False)) 
countries.append(Countries(value="142",description="Mongolia",continent="Asia", selected=False)) 
countries.append(Countries(value="146",description="Myanmar",continent="Asia", selected=False)) 
countries.append(Countries(value="149",description="Nepal",continent="Asia", selected=False)) 
countries.append(Countries(value="161",description="Oman",continent="Asia", selected=False)) 
countries.append(Countries(value="162",description="Pakistan",continent="Asia", selected=False)) 
countries.append(Countries(value="164",description="Palestinian Territory",continent="Asia", selected=False)) 
countries.append(Countries(value="169",description="Philippines",continent="Asia", selected=False)) 
countries.append(Countries(value="174",description="Qatar",continent="Asia", selected=False)) 
countries.append(Countries(value="177",description="Russia",continent="Asia", selected=False)) 
countries.append(Countries(value="187",description="Saudi Arabia",continent="Asia", selected=False)) 
countries.append(Countries(value="192",description="Singapore",continent="Asia", selected=False)) 
countries.append(Countries(value="200",description="Sri Lanka",continent="Asia", selected=False)) 
countries.append(Countries(value="207",description="Syria",continent="Asia", selected=False)) 
countries.append(Countries(value="208",description="Taiwan",continent="Asia", selected=False)) 
countries.append(Countries(value="209",description="Tajikistan",continent="Asia", selected=False)) 
countries.append(Countries(value="211",description="Thailand",continent="Asia", selected=False)) 
countries.append(Countries(value="212",description="Timor-leste",continent="Asia", selected=False)) 
countries.append(Countries(value="218",description="Turkey",continent="Asia", selected=False)) 
countries.append(Countries(value="219",description="Turkmenistan",continent="Asia", selected=False)) 
countries.append(Countries(value="224",description="United Arab Emirates",continent="Asia", selected=False)) 
countries.append(Countries(value="229",description="Uzbekistan",continent="Asia", selected=False)) 
countries.append(Countries(value="232",description="Vietnam",continent="Asia", selected=False)) 
countries.append(Countries(value="237",description="Yemen",continent="Asia", selected=False)) 
countries.append(Countries(value="004",description="American Samoa",continent="Oceania", selected=False)) 
countries.append(Countries(value="013",description="Australia",continent="Oceania", selected=False)) 
countries.append(Countries(value="045",description="Christmas Island",continent="Oceania", selected=False)) 
countries.append(Countries(value="046",description="Cocos (Keeling) Islands",continent="Oceania", selected=False)) 
countries.append(Countries(value="051",description="Cook Islands",continent="Oceania", selected=False)) 
countries.append(Countries(value="302",description="Easter Island",continent="Oceania", selected=False)) 
countries.append(Countries(value="071",description="Fiji",continent="Oceania", selected=False)) 
countries.append(Countries(value="087",description="Guam",continent="Oceania", selected=False)) 
countries.append(Countries(value="100",description="Indonesia",continent="Oceania", selected=False)) 
countries.append(Countries(value="111",description="Kiribati",continent="Oceania", selected=False)) 
countries.append(Countries(value="133",description="Marshall Islands",continent="Oceania", selected=False)) 
countries.append(Countries(value="139",description="Micronesia, Federated States of",continent="Oceania", selected=False)) 
countries.append(Countries(value="148",description="Nauru",continent="Oceania", selected=False)) 
countries.append(Countries(value="152",description="New Caledonia",continent="Oceania", selected=False)) 
countries.append(Countries(value="153",description="New Zealand",continent="Oceania", selected=False)) 
countries.append(Countries(value="157",description="Niue",continent="Oceania", selected=False)) 
countries.append(Countries(value="158",description="Norfolk Island",continent="Oceania", selected=False)) 
countries.append(Countries(value="159",description="Northern Mariana Islands",continent="Oceania", selected=False)) 
countries.append(Countries(value="163",description="Palau",continent="Oceania", selected=False)) 
countries.append(Countries(value="166",description="Papua New Guinea",continent="Oceania", selected=False)) 
countries.append(Countries(value="170",description="Pitcairn",continent="Oceania", selected=False)) 
countries.append(Countries(value="075",description="French Polynesia",continent="Oceania", selected=False)) 
countries.append(Countries(value="184",description="Samoa",continent="Oceania", selected=False)) 
countries.append(Countries(value="195",description="Solomon Islands",continent="Oceania", selected=False)) 
countries.append(Countries(value="214",description="Tokelau",continent="Oceania", selected=False)) 
countries.append(Countries(value="215",description="Tonga",continent="Oceania", selected=False)) 
countries.append(Countries(value="221",description="Tuvalu",continent="Oceania", selected=False)) 
countries.append(Countries(value="230",description="Vanuatu",continent="Oceania", selected=False)) 


class MediaTypeChoices(db.Model): #this table is never stored 
    value    = db.StringProperty() 
    selected = db.BooleanProperty() 
 
mediaTypeChoices = []
mediaTypeChoices.append(MediaTypeChoices(value="blog",selected=False)) 
mediaTypeChoices.append(MediaTypeChoices(value="audio",selected=False)) 
mediaTypeChoices.append(MediaTypeChoices(value="video",selected=False)) 
mediaTypeChoices.append(MediaTypeChoices(value="picture",selected=False)) 
mediaTypeChoices.append(MediaTypeChoices(value="link",selected=False)) 

 
class AppliesToChoices(db.Model): #this table is never stored 
    value    = db.StringProperty() 
    selected = db.BooleanProperty() 
 
appliesToChoices = []
appliesToChoices.append(AppliesToChoices(value="ALL",selected=False)) 
appliesToChoices.append(AppliesToChoices(value="serviceType",selected=False)) 


class AdminStatusChoices(db.Model): #this table is never stored 
    value    = db.StringProperty() 
    selected = db.BooleanProperty() 
 
adminStatusChoices = []
adminStatusChoices.append(AdminStatusChoices(value="software",selected=False)) 
adminStatusChoices.append(AdminStatusChoices(value="billing",selected=False)) 
adminStatusChoices.append(AdminStatusChoices(value="resources",selected=False)) 
adminStatusChoices.append(AdminStatusChoices(value="support",selected=False)) 

 
class DepartmentChoices(db.Model): #this table is never stored 
    value    = db.StringProperty() 
    selected = db.BooleanProperty() 
 
departmentChoices = []
departmentChoices.append(DepartmentChoices(value="software",selected=False)) 
departmentChoices.append(DepartmentChoices(value="billing",selected=False)) 
departmentChoices.append(DepartmentChoices(value="resources",selected=False)) 
departmentChoices.append(DepartmentChoices(value="support",selected=False)) 
departmentChoices.append(DepartmentChoices(value="website",selected=False)) 


class FeedbackTypeChoices(db.Model): #this table is never stored 
    value    = db.StringProperty() 
    selected = db.BooleanProperty() 
 
feedbackTypeChoices = []
feedbackTypeChoices.append(FeedbackTypeChoices(value="feedback",selected=False)) 
feedbackTypeChoices.append(FeedbackTypeChoices(value="defect",selected=False)) 
feedbackTypeChoices.append(FeedbackTypeChoices(value="ticket",selected=False)) 
 



class GoalTypeChoices(db.Model): #this table is never stored 
    value    = db.StringProperty() 
    selected = db.BooleanProperty() 
 
goalTypeChoices = []
goalTypeChoices.append(GoalTypeChoices(value="Education",selected=False)) 
goalTypeChoices.append(GoalTypeChoices(value="Career",selected=False)) 
goalTypeChoices.append(GoalTypeChoices(value="Personal",selected=False)) 
goalTypeChoices.append(GoalTypeChoices(value="Family",selected=False)) 
goalTypeChoices.append(GoalTypeChoices(value="Charity ",selected=False)) 
 


class KnowledgeTypeChoices(db.Model): #this table is never stored 
    value    = db.StringProperty() 
    selected = db.BooleanProperty() 
 
knowledgeTypeChoices = []
knowledgeTypeChoices.append(KnowledgeTypeChoices(value="book",selected=False)) 
knowledgeTypeChoices.append(KnowledgeTypeChoices(value="meeting",selected=False)) 
knowledgeTypeChoices.append(KnowledgeTypeChoices(value="conference",selected=False)) 
knowledgeTypeChoices.append(KnowledgeTypeChoices(value="video",selected=False)) 
knowledgeTypeChoices.append(KnowledgeTypeChoices(value="audioperiodical",selected=False)) 
knowledgeTypeChoices.append(KnowledgeTypeChoices(value="vacation",selected=False)) 
knowledgeTypeChoices.append(KnowledgeTypeChoices(value="class ",selected=False)) 
 

class EventTypeChoices(db.Model): #this table is never stored 
    value    = db.StringProperty() 
    selected = db.BooleanProperty() 
 
eventTypeChoices = []
eventTypeChoices.append(EventTypeChoices(value="started",selected=False)) 
eventTypeChoices.append(EventTypeChoices(value="completed chapter",selected=False)) 
eventTypeChoices.append(EventTypeChoices(value="completed",selected=False)) 
eventTypeChoices.append(EventTypeChoices(value="remember ",selected=False)) 
 

class PayloadTypeChoices(db.Model): #this table is never stored 
    value    = db.StringProperty() 
    selected = db.BooleanProperty() 
 
payloadTypeChoices = []
payloadTypeChoices.append(PayloadTypeChoices(value="text",selected=False)) 
payloadTypeChoices.append(PayloadTypeChoices(value="video",selected=False)) 
payloadTypeChoices.append(PayloadTypeChoices(value="audio ",selected=False)) 
 

